yokoffing/filterlists

- enhanced_site_protection.txt
I was using a Discord verification bot and the verification page was blocked.
Discord bot invite link: `https://discord.com/api/oauth2/authorize?client_id=1014100705763659817&permissions=8&scope=applications.commands%20bot` (I think only the owner can configure the bot)
the message from the bot
> nsverify.shop

- block_third_party_fonts.txt
`fonts.google.com` doesn't show fonts when `fonts.googleapis.com` is blocked
> fonts.google.com

- README.md
- privacy_essentials.txt
`discohook.org` needs `discord.com` to send webhook messages on discord
> discohook.org

- privacy_essentials.txt
cdn-apple.com is whitelisted on apple.com, but needs to be whitelisted on icloud.com for login to work.
> Ensuring Apple login works on iCloud

- personal.txt
When a video is fullscreened, an unwanted and unnecessary *vertical* scrollbar is shown on Firefox v86 and above (not to be confused with the horizontal scrollbar, which scrolls up and down and is on the right edge of the screen).
The vertical scrollbar serves no use in fullscreen, dragging it around does nothing.
I didn't think that this would be appropriate for the annoyance filter, so I added it to the personal one, since I couldn't think of a reason that someone could dislike this addition. In case I'm intruding your personal list, you can feel free to reject the PR.
This only occurs on firefox (for some reason).
See the attached image (the gray line at the bottom is the vertical scroll bar. It may look different for you, since I have a firefox theme applied.)
> Hide horizontal scrollbar on YouTube in fullscreen mode

- personal.txt
Currently, the filter only hides the view count element. The element that follows it, i.e., the date, has a leading seperator dot ("•"), which seperates the view count and the date. Since the view count is removed, that seperator is redundant and clutters up the UI.
Additionally, it seems like the `www.youtube.com###span.ytd-grid-video-renderer.style-scope:nth-of-type(1)` filter seems redundant, as there doesn't seem to be element that is removed by it, neither in subscriptions nor in the homepage. So I've removed it. If I'm wrong, then feel free to correct me and I'll accordingly revert the removal of that filter.
> Hide the leading seperator as well in the "Hide View count on Home, ..." filter

- youtube_clear_view.txt
While originally writing the filter, I assumed that uBO overwrites the style tag of the element to apply css, so I used :watch-attr() so that uBO makes sure that it is set to -1px even when youtube resets it. 
However, as it turns out, uBO doesn't overwrite the style tag. It instead adds some gibberish attributes to the element and uses that as a selector and injects the css for that selector. Since my css already has `!important`, it takes more specificity than youtube's css in the style tag. So, the :watch-attr() operator is useless.
> Address an oversight in the hide horizontal scrollbar filter

- youtube_clear_view.txt
Recently, YouTube recieved a UI update and now stats like the like count and view count automatically live-update under the video player. You can see how it looks like [here](https://www.reddit.com/r/youtube/comments/15c7ndi/youtube_has_added_live_updating_view_counts/). It is quite distracting, especially because it has an animation.
This PR stops stats from live updating, by blocking the endpoint from which the updated stats are fetched.
> Prevent stats from live-updating

- youtube_clear_view.txt
Hide badges (such as "New") under video recommendations on the sidebar.
At first, I was going to only remove the "New" badge under videos, but now that I think about it, the badges only clutter up the UI. You can see all of the badges (such as "Fundraiser") under the video player, so there's no need for it under the video recommendations, and using `:has-text()` (which is a procedural filter, i.e. it uses javascript) to only target the "New" badge will make it less efficient as well.
> [youtube_clear_view] Hide badges under video recommendations

- youtube_clear_view.txt
In some videos, above the transcripts section in the description, a shorts section is shown.
The content highlighted in red is removed by this filter.
> Hide shorts shelf in description

- youtube_clear_view.txt
Example: https://www.youtube.com/watch?v=l_LsO3I_41M&t=11s
At 0:12, the subscribe button will have a rainbow-colored border animation around it for about a second.
Whenever someone says "subscribe", or "like" in the video, the respective elements get this animation. As you can tell, it is annoying unnecessary and distracting. For more info, see [this reddit thread](https://www.reddit.com/r/youtube/comments/15ri8fp/the_subscribe_button_now_plays_an_animation_when/)
The filter removes everything in the `yt-smartimation` element except than the content itself, i.e., removing the animation.
This can also be handled by setting some experiment flags, which are checked for in YouTube's `desktop_polymer_enable_wil_icons.js` script:
```
www.youtube.com##+js(set, …
```
> [youtube_clear_view] Hide new "smartimation" animations

- youtube_clear_view.txt
A few reasons for this proposal:
* YouTube's detection mechanisms are rapidly changing. If you add filters related to detection/slowdowns/etc to your lists, it will only increase burden for uBO volunteers as they have to tell users to disable your list if it's causing a breakage/detection.
* Your source for the filters is ghacks, despite the fact that the filters from that article are actually outdated. The latest slowdown fix filters are in the [YouTube issue in the uAssets repo](https://github.com/uBlockOrigin/uAssets/issues/20586).
* The filter checks if firefox is active, which is misleading since the slowdown happens on all browsers, it's just that only some specific users have it.
> Remove youtube delay fix

- privacy_essentials.txt
causes breakage
test link: `https://oldgoogle.neocities.org/2010/search/?sclient=psy&hl=en&site=webhp&source=hp&q=test&btnG=Search`
> add exception oldgoogle.neocities.org

- block_third_party_fonts.txt
Unfortunately, fonts are broken on these domains without `fonts.gstatic.com` being allowed.
Ex. [`cloudskillsboost.google`](https://cloudskillsboost.google):
& [`career.skills.google`](https://career.skills.google):
> Fix cloudskillsboost.google & skills.google

- click2load.txt
Without this exception, YouTube videos embedded in articles from The Guardian are simply stuck on a black screen and will not play.
Article as an example:
https://www.theguardian.com/us-news/2018/oct/22/donald-trump-ted-cruz-rally-houston-midterms-obama-vegas
This fixes it.
> Unbreak The Guardian YouTube Video Playback

- block_third_party_fonts.txt
Certain icons on Plex are broken without allowing fonts from `amazonaws.com` - most notably when attempting to edit a library.
Ex. before this fix:
After:
> Fix plex.tv

- block_third_party_fonts.txt
This fixes display issues with Android Code Search (`cs.android.com`). Can be seen ex. [here](https://cs.android.com/android/platform/superproject/main):
> Fix cs.android.com

- block_third_party_fonts.txt
When `fonts.googleapis.com` is blocked, DigitalOcean's log-in/registration page *(ex. https://cloud.digitalocean.com/login)* loads a blank page:
This fixes it.
> Fix cloud.digitalocean.com

- block_third_party_fonts.txt
`fonts.googleapis.com` appears to be required for instances of AdvancedMD's [Patient Portal](https://www.advancedmd.com/patient/portal-software/).
Ex. *(`https://pp-wfe-101.advancedmd.com/157958/account/logon`)*:
With `fonts.googleapis.com` blocked:
With `fonts.googleapis.com` allowed:
> Fix advancedmd.com

- click2load.txt
This exception fixes automatic YouTube playback when you press the play button on a song.
Example:
Just click the YouTube play icon at the bottom, and wait. The video will never play because the click2load prompt is hidden.
https://www.songsterr.com/a/wsa/metallica-master-of-puppets-tab-s455118
> Fix Songsterr Youtube Playback

- block_third_party_fonts.txt
`fonts.googleapis.com` being blocked here results in a black/empty page *(ex. https://riverside.fm/studio/adsad)*, this fixes it.
With `fonts.googleapis.com` blocked:
With `fonts.googleapis.com` unblocked:
> Fix riverside.fm
